// <auto-generated />
namespace Playlistify.DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updatetheuser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatetheuser));
        
        string IMigrationMetadata.Id
        {
            get { return "202312010300302_update the user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
